#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("YetAnotherAppAndroid.Resource", IsApplication=true)]

namespace YetAnotherAppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int c = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int e = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int f = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int g = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int h = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int i = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int j = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int k = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int l = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int m = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int n = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int o = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int p = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int q = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int r = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int s = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int t = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int u = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Grid = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int title = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
